_description: |
  The base layout of my pages

head:
  _componentList:
    page: true
    include:
      - clay-meta-title

main:
  _placeholder:
    text: Main Section
    height: 600px
  _componentList:
    page: true
    include:
      - page-header

kiln:
  _component:
    include:
      - clay-kiln
