_description: The base layout of my pages

head:
  _componentList:
    page: true

main:
  _placeholder:
    text: Main Section
    height: 600px
  _componentList:
    page: true

foot:
  _placeholder:
    text: Footer Section
    height: 300px
  _componentList: true

kiln:
  _componentList:
    include:
      - clay-kiln
